import TranslationJob from '../../models/TranslationJob.js';
import TranslationOperationalAlert from '../../models/TranslationOperationalAlert.js';
import { getTranslationOperationalHealth } from './translationHealthService.js';
import { getActiveTranslationConfiguration } from './translationConfigurationService.js';

const open = (type, severity, summary, metadata) => TranslationOperationalAlert.findOneAndUpdate({ dedupeKey: `${type}:${Math.floor(Date.now() / 300000)}` }, { $setOnInsert: { type, severity, summary, metadata, dedupeKey: `${type}:${Math.floor(Date.now() / 300000)}`, expiresAt: new Date(Date.now() + 730 * 86400000) } }, { returnDocument: 'after', upsert: true });
export const evaluateOperationalAlerts = async () => { const [health, config, dead] = await Promise.all([getTranslationOperationalHealth(), getActiveTranslationConfiguration(), TranslationJob.countDocuments({ status: 'dead_letter' })]); const backlog = health.queue.filter((x) => ['queued', 'retry_scheduled'].includes(x._id)).reduce((n, x) => n + x.count, 0); const alerts = []; if (!health.provider.available) alerts.push(await open('provider_unavailable', 'critical', 'Configured provider is unavailable', { provider: health.provider.active })); if (dead) alerts.push(await open('dead_letter', 'critical', 'Translation jobs are in dead letter', { count: dead })); if (backlog >= config.alerts.queuedOrRetryThreshold) alerts.push(await open('queue_backlog', 'warning', 'Translation queue backlog threshold reached', { backlog })); if (health.rollingFailureRatePercent >= config.alerts.rollingFailureRatePercent) alerts.push(await open('failure_rate', 'warning', 'Translation failure-rate threshold reached', { rate: health.rollingFailureRatePercent })); return alerts; };
export const listOperationalAlerts = () => TranslationOperationalAlert.find().sort({ createdAt: -1 }).lean();
export const updateOperationalAlert = (id, status, actor) => TranslationOperationalAlert.findByIdAndUpdate(id, { $set: { status, ...(status === 'acknowledged' ? { acknowledgedBy: actor, acknowledgedAt: new Date() } : {}) } }, { returnDocument: 'after', runValidators: true });
