export const ADVERTISING_POLICY_PAGE_KEY = 'advertising-policy';
export const ADVERTISING_POLICY_OBJECT_ID = '000000000000000000000001';

export const advertisingPolicyContent = Object.freeze({
  "hero": {
    "title": "Advertising",
    "accent": "Policy",
    "brand": "World Culture Marketplace (WCM)",
    "updatedLabel": "Last updated",
    "updatedDate": "30 April 2026"
  },
  "tableOfContentsLabel": "Table of Contents",
  "segments": [
    "Scope of Advertising Services",
    "Advertiser Eligibility",
    "Advertising Content Requirements",
    "Approval & Review Process",
    "Fees, Payments & Billing",
    "Ad Delivery, Performance & Limitations",
    "Ad Placement & Visibility Logic",
    "Sponsored Content Rules",
    "Intellectual Property Rights",
    "Prohibited Practices",
    "Termination or Removal of Ads",
    "Limitation of Liability",
    "No Exclusivity",
    "Indemnification",
    "Modifications",
    "Contact Information",
    "Governing Law",
    "These Advertising & Sponsored Content Rules",
    "(\"Advertising Terms\")",
    "govern the purchase, submission, display, and management of advertising and paid promotional content",
    "(\"Ads\")",
    "on the World Culture Marketplace platform",
    "(\"WCM\", \"we\", \"our\")",
    ".",
    "Advertisers",
    "(\"You\", \"Advertiser\", \"Client\")",
    "must comply with these Terms as well as:",
    "the WCM Terms & Conditions",
    "the Privacy Policy",
    "the Community Standards",
    "By submitting or purchasing advertising on WCM, you agree to all terms below.",
    "Section 01",
    "WCM offers several types of promotional services, including but not limited to:",
    "Banner advertisements",
    "Sponsored cultural articles",
    "Featured placement blocks",
    "Boosted visibility listings (“Boost”)",
    "Pay-per-click (PPC) campaigns",
    "Cultural brand visibility programs",
    "Section 02",
    "Advertisers must:",
    "Be at least 18 years old",
    "Legally represent the brand or content being advertised",
    "Provide accurate billing and contact information",
    "Comply with cultural respect, intellectual property, and applicable advertising laws",
    "WCM reserves the right to accept or refuse any advertiser or campaign at its sole discretion.",
    "Section 03",
    "Advertisers must ensure that all advertising materials:",
    "Are accurate and not misleading",
    "Respect cultural groups, traditions, and identities",
    "Do not exploit, misrepresent, or distort cultural heritage",
    "Comply with all applicable laws and regulations",
    "Do not infringe copyright, trademark, or other intellectual property rights",
    "Are technically safe and free from malicious elements",
    "Prohibited content includes (but is not limited to):",
    "Misleading health or financial claims",
    "Culturally disrespectful or appropriative imagery",
    "Counterfeit or illegal goods",
    "Explicit or adult content",
    "Unapproved political advertising",
    "Discriminatory or harmful content",
    "Unlicensed sale of culturally restricted artifacts",
    "WCM reserves the right to reject, modify, or remove any content at its discretion.",
    "Section 04",
    "All advertising content is subject to review and approval by the WCM team.",
    "WCM may reject or remove advertisements that:",
    "Violate these Advertising Terms",
    "Violate cultural sensitivity principles",
    "Contain misleading or harmful claims",
    "Harm the reputation of WCM or represented communities",
    "Contain broken links or unsafe technical elements",
    "Note:",
    "WCM reserves the right to adjust formatting, layout, or placement of any approved advertisement for technical or design reasons to ensure a seamless user experience.",
    "Section 05",
    "5.1 — Payment Terms",
    "Advertisers agree that:",
    "Fees must be paid in advance unless otherwise agreed in writing",
    "All payments for advertising services, including Boost and PPC, are final and non-refundable, except where required by applicable law",
    "Invoices must be paid within the stated timeframe provided during the checkout process",
    "5.2 — PPC & Boosted Visibility",
    "For exposure-based services such as Pay-Per-Click (PPC) and Boosted Listings:",
    "Charges may apply per click, impression, or duration depending on the selected plan",
    "Click tracking is based on WCM’s internal measurement systems",
    "WCM implements reasonable measures to detect invalid or fraudulent activity but does not guarantee complete prevention",
    "Reported metrics (clicks, impressions) may be subject to verification and adjustment",
    "Unused credits may expire according to the applicable plan terms",
    "Important Disclaimer:",
    "Boosted visibility services provide increased exposure only and do not guarantee specific results, including views, clicks, or sales. Visibility, traffic, and performance are not guaranteed.",
    "5.3 — Non-Payment",
    "WCM may suspend or remove advertising services immediately in the event of:",
    "Late payments",
    "Failed transactions",
    "Section 06",
    "Advertisers acknowledge that:",
    "WCM does not guarantee traffic, sales, leads, or conversions",
    "Visibility may vary depending on user behavior and platform dynamics",
    "System maintenance, outages, or technical issues may impact delivery",
    "WCM shall not be responsible for fluctuations in performance",
    "WCM is a visibility and discovery platform, not a sales platform",
    "Advertisers remain solely responsible for the performance and outcomes of their external websites or services",
    "Section 06B",
    "WCM operates a hybrid visibility model combining organic curation and paid promotion.",
    "Paid placements (Boost, PPC, Featured listings) may appear alongside organic content",
    "WCM does not guarantee exclusive placement or category dominance",
    "Competing creators or advertisers may appear in the same sections",
    "Placement is determined by multiple factors including:",
    "Paid promotion settings",
    "Your bid and campaign configuration",
    "Editorial curation",
    "Hand-picked selections by WCM team",
    "User engagement",
    "How the community interacts with content",
    "Platform algorithms",
    "Automated relevancy and discovery logic",
    "WCM reserves the right to organize, rank, and display content to preserve:",
    "Platform balance",
    "User experience",
    "Cultural integrity",
    "Section 07",
    "Sponsored content must:",
    "Be clearly labeled as “Sponsored”",
    "Comply with Community Standards",
    "Respect cultural sensitivities",
    "Avoid misleading or false messaging",
    "Labeling & Formatting",
    "WCM reserves the right to label content as:",
    "“Sponsored”",
    "“Promoted”",
    "“Featured”",
    "WCM may adjust layout or formatting for editorial consistency to ensure all sponsored content blends seamlessly with the platform's visual standards.",
    "Section 08",
    "Advertisers must hold all necessary rights or licenses for:",
    "Images",
    "Logos",
    "Videos",
    "Text and copy",
    "Illustrations",
    "License Grant to WCM",
    "By submitting content, advertisers grant WCM a non-exclusive, worldwide, royalty-free license to:",
    "Publish",
    "Display",
    "Store",
    "Resize or reformat",
    "Distribute for advertising and platform purposes",
    "Section 09",
    "To maintain the integrity of our marketplace, Advertisers may not:",
    "Submit fraudulent or misleading information",
    "Impersonate individuals or brands",
    "Artificially inflate clicks or impressions",
    "Use automated systems to manipulate visibility metrics",
    "Bypass platform controls or review systems",
    "Promote illegal or culturally harmful content",
    "Any attempt to engage in these practices will result in immediate campaign suspension and potential account ban.",
    "Section 10",
    "WCM reserves the right to suspend or remove advertisements if:",
    "These Advertising Terms are violated",
    "Credible cultural or legal complaints are received regarding the content",
    "Safety or reputational risks arise for WCM or its community",
    "Removal may occur without prior notice in serious cases to protect platform integrity.",
    "To the maximum extent permitted by law, WCM shall not be liable for:",
    "Loss of revenue or business opportunities",
    "Reduced advertising performance",
    "Cultural disputes or disagreements",
    "Technical failures or downtime",
    "Third-party misuse of content",
    "Indirect or consequential damages",
    "Advertisers use WCM at their own risk.",
    "Unless explicitly agreed in writing:",
    "Advertising placements on WCM are non-exclusive",
    "Multiple advertisers may appear simultaneously",
    "Competitors may be displayed in similar contexts",
    "No guarantee of exclusive audience or category dominance",
    "WCM does not guarantee exclusivity of placement.",
    "Section 12",
    "Advertisers agree to indemnify and hold harmless WCM from claims arising from:",
    "Intellectual property violations",
    "Misleading or unlawful advertising",
    "Cultural misrepresentation or harm",
    "Regulatory or legal breaches",
    "This protection extends to WCM’s directors, employees, and community representatives against any third-party claims.",
    "Section 13",
    "WCM may update these Terms at any time.",
    "Updates take effect upon publication on the platform.",
    "Advertisers are encouraged to review this page periodically for any changes.",
    "Section 15",
    "These Advertising Terms shall be governed by the laws of France.Any disputes shall be subject to the jurisdiction of the courts of Paris, France, unless otherwise required by applicable law."
  ],
  "contact": {
    "number": "Section 14",
    "title": "Contact Information",
    "intro": "For advertising inquiries:",
    "brand": "World Culture Marketplace (WCM)",
    "emailLabel": "contact@worldculturemarketplace.com",
    "parisLabel": "50 Avenue des Champs-?lys?es, 75008 Paris, France.",
    "washingtonLabel": "Washington, USA."
  },
  "imageAlt": "World Culture Marketplace advertising policy"
});

