export const BOOST_TERMS_PAGE_KEY = 'boost-terms-and-ppc';

export const boostTermsContent = Object.freeze({
  businessValues: Object.freeze({
    starter: Object.freeze({ priceEur: 12, durationDays: 7 }),
    standard: Object.freeze({ priceEur: 29, durationDays: 14 }),
    premium: Object.freeze({ priceEur: 79, durationDays: 30 }),
    ppcCostPerClickEur: 0.30,
  }),
  sections: Object.freeze({
    hero: Object.freeze([
      'What is a Boosted Listing', 'on World Culture Marketplace?', 'A Boosted Listing is an',
      'optional promotional feature',
      'that allows creators to increase the visibility of their cultural artwork, handmade crafts, and creative products on World Culture Marketplace.',
      'When a listing is boosted, it may appear in more prominent areas of the platform, helping it reach a',
      'larger audience', 'interested in cultural art and global craftsmanship.', 'Boosted listings can appear in',
      'Featured sections of the homepage', 'Highlighted cultural collections', 'Prioritized search results',
      'Explore pages across the marketplace', 'This helps creators promote their',
      'African crafts, Asian handmade decor, traditional textiles, and cultural creations', ', to more visitors.',
      'WCM Promotional Feature', 'Last updated:', '22 April 2026',
    ]),
    boostPromotion: Object.freeze([
      'How does', 'Boost promotion work?', 'Boost promotion works through a', 'fixed promotional placement',
      'rather than a pay-per-click model.', 'The process typically works as follows',
      'A creator selects a listing they want to promote.', 'The creator activates the Boost option.',
      'The listing receives increased visibility on the platform.',
      'The promotion remains active for a defined period or campaign duration.',
      '"Boosted listings are clearly designed to help creators gain more exposure within the marketplace environment."',
      'Fixed Placement Model', 'WCM Creator Tools',
    ]),
    boostListing: Object.freeze([
      'Why use', 'Boosted Listings?', 'Boosted Listings help creators', 'Increase visibility for new products',
      'Reach more potential buyers', 'Highlight seasonal or featured creations', 'Promote unique cultural artwork',
      'Creators often use boosts to promote:', 'New cultural collections', 'Limited edition crafts',
      'Traditional textile creations', 'Signature artwork pieces', 'Marketplace Growth', 'WCM Creator Success',
    ]),
    creatorBoost: Object.freeze([
      'When should', 'creators use Boost?', 'Creators may benefit from boosting their listings when',
      'Launching new creations', 'Promoting cultural collections', 'Participating in special events or seasonal promotions',
      'Increasing exposure for high-value artwork', 'Pancark', 'Boosting',
      'is a simple way to attract more attention to creations within the marketplace.', 'Creator Strategy', 'WCM Growth Tools',
    ]),
    boostPpcComparison: Object.freeze([
      'How is Boost different from', 'Pay-Per-Click (PPC)?',
      'Both promotional tools help increase visibility, but they work differently.', 'Boosted Listings',
      'fixed promotion fee', 'increased visibility for a defined period', 'no charge based on clicks',
      'simple and predictable promotion', 'Pay-Per-Click (PPC)',
      'creators pay only when a visitor clicks their listing', 'promotion cost depends on engagement',
      'flexible budget control', 'These options give creators different ways to promote their',
      'cultural art, handmade crafts, and creative works.', 'Model Comparison', 'WCM Advertising',
    ]),
    boostMandatory: Object.freeze([
      'Is Boost mandatory to sell on', 'World Culture Marketplace?', 'No.', 'Boosting listings is',
      'completely optional.', 'Creators can publish and showcase their cultural creations on the platform',
      'without using promotional tools.', 'Boost simply provides an', 'additional option',
      'for creators who want to increase visibility.', 'Free to list', 'Optional Boost', 'WCM Creator Terms • 2026 Edition',
    ]),
    promotionBudget: Object.freeze([
      'Can creators control their', 'promotion budget?', 'Yes', 'Creators have', 'full control',
      'over their promotional features.', 'Creators can choose whether or not to use promotional features and decide',
      'which listings they want to promote.',
      'This allows creators to manage their visibility strategy while showcasing their cultural work to a global audience.',
      'Flexible Strategy', 'Full Sovereignty',
    ]),
    payPerClick: Object.freeze([
      'What is Py-Per-Click (PPC)a', 'Py-Per-Click (PPC)a promotion on World Culture Marketplace?',
      'Pay-Per-Click (PPC) is an', 'optional promotional feature',
      'that allows creators to increase the visibility of their cultural artwork, handmade crafts, or creative products on World Culture Marketplace.',
      'With PPC promotion, creators', 'only pay when a visitor clicks',
      'on their promoted listing. This model allows creators to promote their creations while controlling their promotional budget.',
      'PPC listings may appear in areas such as', 'Promoted search results', 'Featured sections of the marketplace',
      'Curated pages', 'This system helps creators gain more exposure for their cultural products while',
      'ensuring that promotional costs are tied to actual user engagement.', 'WCM Advertising Model', 'Effective: 2026',
    ]),
    ppcPromotion: Object.freeze([
      'How does', 'PPC promotion work?',
      'Creators who choose the PPC option set a promotion budget and bid amount for their listing.',
      'The process works as follows', 'The creator activates PPC promotion for a listing.',
      'The listing becomes eligible to appear in promoted sections.',
      'When a visitor clicks the promoted listing, the creator is charged the agreed cost per click.',
      'The listing continues to appear until the creator’s budget limit is reached or the promotion is stopped.',
      '"This allows creators to manage how much they spend while promoting their cultural creations."',
      'Budget Management', 'WCM Advertising System',
    ]),
    listingPpcComparison: Object.freeze([
      'What is the difference between', 'Boosted Listings and PPC?',
      'Both options help creators increase visibility, but they work differently.', 'Boosted Listings',
      'Fixed promotional fee', 'Increased visibility for a defined period', 'No charge per click',
      'Pay-Per-Click (PPC)', 'No upfront fee required', 'Creators pay only when users click their listing',
      'Budget and promotion can be adjusted at any time', 'Both tools allow creators to promote',
      'African crafts, Asian handmade decor, cultural fashion,', 'and other creative works to a global audience.',
      'WCM Advertising Comparison',
    ]),
    creatorsPpc: Object.freeze([
      'Should creators use', 'Boosted Listings or PPC?',
      'The best option depends on the creator’s promotional strategy.', 'Creators who want',
      'simple promotion with predictable cost', 'often prefer Boosted Listings.', 'Creators who want',
      'performance-based promotion and flexible budgets', 'may prefer PPC campaigns.', 'Some creators use',
      'both methods together', 'to maximize visibility on the platform.', 'Strategy Guide • WCM', 'Active Strategy',
    ]),
    boostPricing: Object.freeze([
      'Starter Boost', '7 days', 'boosted search + category pages', 'Standard Boost', '14 days',
      'search + category + explore sections', 'Premium Boost', '30 days',
      'homepage + search + featured collections', 'Boost', 'Pricing Table',
      'Choose the right boost plan for your cultural creations.', 'Boost Type', 'Price', 'Duration', 'Placement',
      'Duration:', 'Placement:', 'Official WCM Pricing • 2026',
    ]),
  }),
});
