export const boostTermsFrenchContent = Object.freeze({
  businessValues: Object.freeze({
    starter: Object.freeze({ priceEur: 12, durationDays: 7 }),
    standard: Object.freeze({ priceEur: 29, durationDays: 14 }),
    premium: Object.freeze({ priceEur: 79, durationDays: 30 }),
    ppcCostPerClickEur: 0.30,
  }),
  sections: Object.freeze({
    hero: Object.freeze([
      'Qu’est-ce qu’une annonce boostée', 'sur World Culture Marketplace ?', 'Une annonce boostée est une',
      'fonctionnalité promotionnelle facultative',
      'qui permet aux créateurs d’accroître la visibilité de leurs œuvres culturelles, objets artisanaux faits main et produits créatifs sur World Culture Marketplace.',
      'Lorsqu’une annonce est boostée, elle peut apparaître dans des zones plus visibles de la plateforme, ce qui l’aide à toucher un',
      'public plus large', 'intéressé par l’art culturel et l’artisanat du monde entier.', 'Les annonces boostées peuvent apparaître dans',
      'les sections mises en avant de la page d’accueil', 'les collections culturelles mises en valeur', 'les résultats de recherche prioritaires',
      'les pages Explorer de la marketplace', 'Cela aide les créateurs à promouvoir leurs',
      'objets d’artisanat africain, décorations asiatiques faites main, textiles traditionnels et créations culturelles', ', auprès d’un plus grand nombre de visiteurs.',
      'Fonctionnalité promotionnelle WCM', 'Dernière mise à jour :', '22 avril 2026',
    ]),
    boostPromotion: Object.freeze([
      'Comment fonctionne', 'la promotion Boost ?', 'La promotion Boost repose sur un', 'emplacement promotionnel à tarif fixe',
      'plutôt que sur un modèle de paiement par clic.', 'Le processus fonctionne généralement comme suit',
      'Un créateur sélectionne une annonce qu’il souhaite promouvoir.', 'Le créateur active l’option Boost.',
      'L’annonce bénéficie d’une visibilité accrue sur la plateforme.',
      'La promotion reste active pendant une période ou une durée de campagne définie.',
      '« Les annonces boostées sont spécialement conçues pour aider les créateurs à gagner en visibilité au sein de la marketplace. »',
      'Modèle à emplacement fixe', 'Outils WCM pour les créateurs',
    ]),
    boostListing: Object.freeze([
      'Pourquoi utiliser', 'les annonces boostées ?', 'Les annonces boostées aident les créateurs à', 'Accroître la visibilité de nouveaux produits',
      'Toucher davantage d’acheteurs potentiels', 'Mettre en valeur des créations saisonnières ou sélectionnées', 'Promouvoir des œuvres culturelles uniques',
      'Les créateurs utilisent souvent les Boosts pour promouvoir :', 'De nouvelles collections culturelles', 'Des créations artisanales en édition limitée',
      'Des créations textiles traditionnelles', 'Des œuvres emblématiques', 'Croissance sur la marketplace', 'Réussite des créateurs WCM',
    ]),
    creatorBoost: Object.freeze([
      'Quand les', 'créateurs devraient-ils utiliser Boost ?', 'Les créateurs peuvent tirer parti du Boost de leurs annonces lorsqu’ils souhaitent',
      'Lancer de nouvelles créations', 'Promouvoir des collections culturelles', 'Participer à des événements spéciaux ou à des promotions saisonnières',
      'Accroître la visibilité d’œuvres de grande valeur', 'Pancark', 'Le Boost',
      'est un moyen simple d’attirer davantage l’attention sur des créations au sein de la marketplace.', 'Stratégie des créateurs', 'Outils de croissance WCM',
    ]),
    boostPpcComparison: Object.freeze([
      'En quoi Boost diffère-t-il du', 'Pay-Per-Click (PPC) ?',
      'Ces deux outils promotionnels permettent d’accroître la visibilité, mais leur fonctionnement diffère.', 'Annonces boostées',
      'frais de promotion fixes', 'visibilité accrue pendant une période définie', 'aucuns frais calculés en fonction des clics',
      'promotion simple et prévisible', 'Pay-Per-Click (PPC)',
      'les créateurs paient uniquement lorsqu’un visiteur clique sur leur annonce', 'le coût de la promotion dépend de l’engagement',
      'contrôle flexible du budget', 'Ces options offrent aux créateurs différentes façons de promouvoir leurs',
      'œuvres culturelles, créations artisanales et œuvres créatives.', 'Comparaison des modèles', 'Publicité WCM',
    ]),
    boostMandatory: Object.freeze([
      'Boost est-il obligatoire pour vendre sur', 'World Culture Marketplace ?', 'Non.', 'Le Boost des annonces est',
      'entièrement facultatif.', 'Les créateurs peuvent publier et présenter leurs créations culturelles sur la plateforme',
      'sans utiliser d’outils promotionnels.', 'Boost offre simplement une', 'option supplémentaire',
      'aux créateurs qui souhaitent accroître leur visibilité.', 'Publication gratuite', 'Boost facultatif', 'Conditions pour les créateurs WCM • Édition 2026',
    ]),
    promotionBudget: Object.freeze([
      'Les créateurs peuvent-ils contrôler leur', 'budget promotionnel ?', 'Oui', 'Les créateurs disposent d’un', 'contrôle total',
      'sur leurs fonctionnalités promotionnelles.', 'Ils peuvent choisir d’utiliser ou non les fonctionnalités promotionnelles et décider',
      'quelles annonces ils souhaitent promouvoir.',
      'Cela leur permet de gérer leur stratégie de visibilité tout en présentant leur travail culturel à un public mondial.',
      'Stratégie flexible', 'Autonomie totale',
    ]),
    payPerClick: Object.freeze([
      'Qu’est-ce que le Pay-Per-Click (PPC)', 'La promotion Pay-Per-Click (PPC) sur World Culture Marketplace ?',
      'Le Pay-Per-Click (PPC) est une', 'fonctionnalité promotionnelle facultative',
      'qui permet aux créateurs d’accroître la visibilité de leurs œuvres culturelles, objets artisanaux faits main ou produits créatifs sur World Culture Marketplace.',
      'Avec la promotion PPC, les créateurs', 'paient uniquement lorsqu’un visiteur clique',
      'sur leur annonce sponsorisée. Ce modèle leur permet de promouvoir leurs créations tout en maîtrisant leur budget promotionnel.',
      'Les annonces PPC peuvent apparaître dans des zones telles que', 'les résultats de recherche sponsorisés', 'les sections mises en avant de la marketplace',
      'les pages éditorialisées', 'Ce système aide les créateurs à accroître la visibilité de leurs produits culturels tout en',
      'garantissant que les coûts promotionnels sont liés à l’engagement réel des utilisateurs.', 'Modèle publicitaire WCM', 'En vigueur : 2026',
    ]),
    ppcPromotion: Object.freeze([
      'Comment fonctionne', 'la promotion PPC ?',
      'Les créateurs qui choisissent l’option PPC définissent un budget promotionnel et un montant d’enchère pour leur annonce.',
      'Le processus fonctionne comme suit', 'Le créateur active la promotion PPC pour une annonce.',
      'L’annonce devient éligible à une apparition dans les sections sponsorisées.',
      'Lorsqu’un visiteur clique sur l’annonce sponsorisée, le coût par clic convenu est facturé au créateur.',
      'L’annonce continue d’apparaître jusqu’à ce que la limite budgétaire du créateur soit atteinte ou que la promotion soit arrêtée.',
      '« Cela permet aux créateurs de maîtriser leurs dépenses tout en faisant connaître leurs créations culturelles. »',
      'Gestion du budget', 'Système publicitaire WCM',
    ]),
    listingPpcComparison: Object.freeze([
      'Quelle est la différence entre', 'les annonces boostées et le PPC ?',
      'Ces deux options aident les créateurs à accroître leur visibilité, mais elles fonctionnent différemment.', 'Annonces boostées',
      'Frais de promotion fixes', 'Visibilité accrue pendant une période définie', 'Aucuns frais par clic',
      'Pay-Per-Click (PPC)', 'Aucuns frais initiaux requis', 'Les créateurs paient uniquement lorsque des utilisateurs cliquent sur leur annonce',
      'Le budget et la promotion peuvent être ajustés à tout moment', 'Ces deux outils permettent aux créateurs de promouvoir',
      'des objets d’artisanat africain, des décorations asiatiques faites main, la mode culturelle,', 'ainsi que d’autres œuvres créatives auprès d’un public mondial.',
      'Comparaison publicitaire WCM',
    ]),
    creatorsPpc: Object.freeze([
      'Les créateurs devraient-ils utiliser', 'les annonces boostées ou le PPC ?',
      'La meilleure option dépend de la stratégie promotionnelle du créateur.', 'Les créateurs qui recherchent une',
      'promotion simple à coût prévisible', 'préfèrent souvent les annonces boostées.', 'Les créateurs qui souhaitent une',
      'promotion basée sur les performances et des budgets flexibles', 'peuvent préférer les campagnes PPC.', 'Certains créateurs utilisent',
      'les deux méthodes conjointement', 'afin de maximiser leur visibilité sur la plateforme.', 'Guide stratégique • WCM', 'Stratégie active',
    ]),
    boostPricing: Object.freeze([
      'Boost Starter', '7 jours', 'recherche boostée + pages de catégories', 'Boost Standard', '14 jours',
      'recherche + catégories + sections Explorer', 'Boost Premium', '30 jours',
      'page d’accueil + recherche + collections mises en avant', 'Boost', 'Tableau des tarifs',
      'Choisissez la formule Boost adaptée à vos créations culturelles.', 'Type de Boost', 'Prix', 'Durée', 'Emplacement',
      'Durée :', 'Emplacement :', 'Tarifs officiels WCM • 2026',
    ]),
  }),
});
