export const CREATOR_TERMS_PAGE_KEY = 'creator-terms-and-conditions';

export const creatorTermsContent = Object.freeze({ segments: Object.freeze([
  'Creator', 'Terms & Conditions', 'World Culture Marketplace (WCM)', 'Last updated:', '30 April 2026',
  'Section 01', 'INTRODUCTION', 'These Creator Terms (', '“Terms”', ') govern the submission of cultural content, images, stories, descriptions, and other materials (',
  '“Content”', ') by creators, researchers, contributors, and cultural organizations (', '“Creators”, “You”', ') to',
  'World Culture Marketplace (“WCM”, “we”, “us”, “our”)', '.', 'By submitting or publishing content on the Platform, you accept and agree to these Terms.',
  'Section 02', 'PURPOSE OF THESE TERMS', 'The Creator Terms establish:', '01', 'what Creators may submit', '02', 'what rights Creators retain',
  '03', 'what license WCM receives', '04', 'cultural responsibility expectations', '05', 'content restrictions', '06', 'conditions for removal or suspension',
  '"Creators are essential to', 'WCM’s mission', 'of celebrating global culture respectfully and accurately."',
  'Eligibility to Submit Content', 'To publish content on WCM, you must:', 'be at least 18 years old', 'have the legal right to submit the content',
  'accept these Terms and the Community Standards', 'provide accurate, non-misleading cultural information', 'comply with all applicable laws',
  'Organizations may contribute through authorized representatives.', 'Section 03', 'TYPES OF CONTENT COVERED', 'These Terms apply to:',
  'cultural descriptions', 'stories, traditions, and historical information', 'images, photos, artwork, illustrations', 'videos or audio (if enabled)',
  'creator bios and external links', 'written educational content', 'any materials uploaded to WCM', 'Section 04', 'OWNERSHIP OF CONTENT',
  '4.1 You Retain Ownership', 'Creators maintain full ownership of all their submitted content, including:', 'copyrights', 'intellectual property rights',
  'authorship', 'This Agreement does not transfer ownership to WCM.', 'Section 05', 'LICENSE GRANTED TO WCM', 'By submitting content, you grant',
  'WCM', 'a non-exclusive, worldwide, royalty-free, transferable, and sub-licensable license to:', 'display', 'reproduce', 'publish', 'distribute',
  'archive', 'translate (if needed)', 'adapt for formatting or accessibility', 'promote on WCM-operated channels',
  'feature in cultural or educational initiatives', 'Purpose:', 'This license exists solely to allow WCM to operate the Platform and celebrate cultural heritage.',
  'Creators may request removal of their content at any time .', 'Section 06', 'CREATOR RESPONSIBILITIES',
  'To maintain the integrity of our marketplace, Creators must:', 'ensure they own or control the rights to submit content',
  'represent cultural information truthfully', 'respect cultural sensitivities, especially sacred traditions', 'avoid misappropriation or exploitation',
  'avoid defamatory or harmful material', 'ensure individuals shown in images have granted consent', 'properly reference sources when possible',
  'Creators are responsible for', 'legal, cultural, and ethical compliance', 'Responsibility includes maintaining', 'account confidentiality',
  'and all activities under your account.', 'Section 07', 'EXTERNAL LINKS & PLATFORM ROLE',
  'Creators are solely responsible for any external websites, products, services, or transactions linked through their content.',
  'WCM does not control, verify, or guarantee the accuracy, safety, or legality of external websites.',
  'Any interaction or engagement with third-party websites is at the user’s own risk.', 'Platform Role:',
  'WCM operates as a discovery and visibility platform only and does not act as a seller, reseller, or intermediary in transactions.',
  'Creators are solely responsible for complying with applicable tax, legal, and regulatory obligations related to their activities.',
  'Section 08', 'PROHIBITED SUBMISSIONS', 'Creators may NOT submit content that:', 'misrepresents cultural origins or meanings',
  'depicts secret or sacred practices without authorization', 'infringes copyrights or trademarks', 'exploits communities or identities',
  'promotes discrimination or hate', 'includes explicit or violent imagery', 'contains malware or harmful code',
  'is commercial advertising disguised as culture', 'Such content may be removed immediately without warning.', 'Section 09',
  'SPONSORED OR COMMERCIAL CONTENT', 'If content is created in partnership with a brand or business:', 'sponsorship must be clearly disclosed',
  'the content must remain culturally respectful', 'the promotional nature must be transparent',
  '* Failure to disclose sponsorship is a violation of these Terms.', 'Promotional Services',
  'Creators who use paid promotional services (such as', 'Boost', 'or', 'PPC', ') are also subject to the', 'Advertising Policy',
  'Section 10', 'REMOVAL OF CONTENT', 'Creators may request content removal for any reason by emailing:', 'contact@worldculturemarketplace.com',
  'WCM may also remove content if it:', 'violates these Terms', 'receives credible cultural or legal complaints', 'infringes intellectual property',
  'causes harm to communities or individuals', 'is misleading, fraudulent, or inappropriate', 'damages WCM’s reputation or mission',
  '* Removed content may remain temporarily in system backups for legal and security compliance.', 'Section 11',
  'CREATOR ACCOUNT SUSPENSION OR TERMINATION', 'WCM may suspend or terminate creator accounts for:', 'repeated violations', 'harmful behavior',
  'cultural misappropriation', 'copyright infringement', 'harassment of users', 'dangerous or abusive conduct',
  'Creators may request account deletion at any time.', 'Contact Support', 'Section 12', 'NO GUARANTEE OF VISIBILITY OR COMPENSATION',
  'Unless explicitly agreed in writing:', 'WCM does not pay Creators for submissions', 'WCM does not guarantee visibility or engagement',
  'WCM does not guarantee featuring of content', 'WCM does not guarantee commercial outcomes',
  'Visibility depends on platform algorithms and editorial decisions.', 'Section 13', 'LIMITATION OF LIABILITY',
  'To the maximum extent allowed by law,', 'is not liable for:', 'disputes involving creator-submitted content',
  'third-party use or misuse of published content', 'cultural disagreements or misinterpretation', 'reputational impact on Creators',
  'damages arising from publication or removal', 'Creators publish on WCM at their own risk.', 'Section 14', 'FORCE MAJEURE',
  'shall not be liable for any failure or delay resulting from events beyond its reasonable control, including:',
  'Technical Failures', 'System Outages', 'External Events', '* This includes any event beyond the reasonable control of the platform and its operators.',
  'Section 15', 'MODIFICATIONS TO THIS AGREEMENT', 'WCM may update these Creator Terms periodically to reflect platform growth or legal changes.',
  'Changes take effect immediately upon publication', 'Please review this page regularly for any revisions.', 'LAST UPDATED:',
  'Section 16', 'CONTACT INFORMATION', 'For questions, concerns, or removal requests regarding these terms, please reach out to the',
  'team.', 'Official Email', 'Business Location', '50 Avenue des Champs-Élysées, 75008 Paris, France.', 'Washington, USA.',
  '©', 'World Culture Marketplace. All rights reserved.', 'Global Heritage • Digital Discovery', 'Section 17', 'GOVERNING LAW',
  'These Terms shall be governed by and construed in accordance with the', 'laws of France',
  'Any disputes shall be subject to the exclusive jurisdiction of the', 'courts of Paris, France', ', unless otherwise required by applicable law.',
  'End of Agreement',
]) });

export const creatorTermsFrenchContent = Object.freeze({ segments: Object.freeze([
  'Créateurs', 'Conditions générales', 'World Culture Marketplace (WCM)', 'Dernière mise à jour :', '30 avril 2026',
  'Section 01', 'INTRODUCTION', 'Les présentes Conditions pour les créateurs (', '« Conditions »', ') régissent la soumission de contenus culturels, images, récits, descriptions et autres éléments (',
  '« Contenu »', ') par les créateurs, chercheurs, contributeurs et organisations culturelles (', '« Créateurs », « Vous »', ') à',
  'World Culture Marketplace (« WCM », « nous », « notre », « nos »)', '.', 'En soumettant ou en publiant du contenu sur la Plateforme, vous acceptez les présentes Conditions.',
  'Section 02', 'OBJET DES PRÉSENTES CONDITIONS', 'Les Conditions pour les créateurs définissent :', '01', 'ce que les Créateurs peuvent soumettre', '02', 'les droits que les Créateurs conservent',
  '03', 'la licence accordée à WCM', '04', 'les exigences en matière de responsabilité culturelle', '05', 'les restrictions applicables au contenu', '06', 'les conditions de retrait ou de suspension',
  '« Les Créateurs sont essentiels à', 'la mission de WCM', 'qui consiste à célébrer les cultures du monde avec respect et exactitude. »',
  'Conditions requises pour soumettre du contenu', 'Pour publier du contenu sur WCM, vous devez :', 'avoir au moins 18 ans', 'disposer du droit légal de soumettre le contenu',
  'accepter les présentes Conditions et les Standards de la communauté', 'fournir des informations culturelles exactes et non trompeuses', 'respecter toutes les lois applicables',
  'Les organisations peuvent contribuer par l’intermédiaire de représentants autorisés.', 'Section 03', 'TYPES DE CONTENU CONCERNÉS', 'Les présentes Conditions s’appliquent aux éléments suivants :',
  'descriptions culturelles', 'récits, traditions et informations historiques', 'images, photographies, œuvres d’art et illustrations', 'vidéos ou contenus audio (si cette fonction est activée)',
  'biographies de créateurs et liens externes', 'contenus éducatifs écrits', 'tout élément téléversé sur WCM', 'Section 04', 'PROPRIÉTÉ DU CONTENU',
  '4.1 Vous conservez la propriété', 'Les Créateurs conservent l’entière propriété de tous les contenus qu’ils soumettent, notamment :', 'droits d’auteur', 'droits de propriété intellectuelle',
  'qualité d’auteur', 'Le présent Accord ne transfère aucun droit de propriété à WCM.', 'Section 05', 'LICENCE ACCORDÉE À WCM', 'En soumettant du contenu, vous accordez à',
  'WCM', 'une licence non exclusive, mondiale, gratuite, transférable et pouvant faire l’objet d’une sous-licence afin de :', 'afficher', 'reproduire', 'publier', 'distribuer',
  'archiver', 'traduire (si nécessaire)', 'adapter à des fins de mise en forme ou d’accessibilité', 'promouvoir sur les canaux exploités par WCM',
  'présenter dans le cadre d’initiatives culturelles ou éducatives', 'Objet :', 'Cette licence vise uniquement à permettre à WCM d’exploiter la Plateforme et de célébrer le patrimoine culturel.',
  'Les Créateurs peuvent demander le retrait de leur contenu à tout moment.', 'Section 06', 'RESPONSABILITÉS DES CRÉATEURS',
  'Afin de préserver l’intégrité de notre marketplace, les Créateurs doivent :', 's’assurer qu’ils détiennent ou contrôlent les droits nécessaires pour soumettre le contenu',
  'présenter les informations culturelles avec exactitude', 'respecter les sensibilités culturelles, notamment les traditions sacrées', 'éviter toute appropriation abusive ou exploitation',
  'éviter tout contenu diffamatoire ou préjudiciable', 's’assurer que les personnes figurant sur les images ont donné leur consentement', 'citer correctement les sources dans la mesure du possible',
  'Les Créateurs sont responsables du', 'respect des obligations légales, culturelles et éthiques', 'Cette responsabilité comprend la protection de', 'la confidentialité du compte',
  'ainsi que de toutes les activités effectuées depuis votre compte.', 'Section 07', 'LIENS EXTERNES ET RÔLE DE LA PLATEFORME',
  'Les Créateurs sont seuls responsables des sites web externes, produits, services ou transactions associés à leur contenu.',
  'WCM ne contrôle pas, ne vérifie pas et ne garantit pas l’exactitude, la sécurité ou la légalité des sites web externes.',
  'Toute interaction avec des sites web tiers s’effectue aux risques de l’utilisateur.', 'Rôle de la Plateforme :',
  'WCM agit uniquement comme une plateforme de découverte et de visibilité et n’intervient pas comme vendeur, revendeur ou intermédiaire dans les transactions.',
  'Les Créateurs sont seuls responsables du respect des obligations fiscales, légales et réglementaires applicables à leurs activités.',
  'Section 08', 'SOUMISSIONS INTERDITES', 'Les Créateurs ne doivent PAS soumettre de contenu qui :', 'présente de manière inexacte les origines ou significations culturelles',
  'dépeint des pratiques secrètes ou sacrées sans autorisation', 'porte atteinte à des droits d’auteur ou à des marques', 'exploite des communautés ou des identités',
  'encourage la discrimination ou la haine', 'comporte des images explicites ou violentes', 'contient des logiciels malveillants ou du code nuisible',
  'dissimule une publicité commerciale sous la forme d’un contenu culturel', 'Un tel contenu peut être retiré immédiatement et sans avertissement.', 'Section 09',
  'CONTENU SPONSORISÉ OU COMMERCIAL', 'Si le contenu est créé en partenariat avec une marque ou une entreprise :', 'le parrainage doit être clairement indiqué',
  'le contenu doit rester respectueux des cultures', 'la nature promotionnelle doit être transparente',
  '* Le défaut de déclaration d’un parrainage constitue une violation des présentes Conditions.', 'Services promotionnels',
  'Les Créateurs qui utilisent des services promotionnels payants (tels que', 'Boost', 'ou', 'PPC', ') sont également soumis à la', 'Politique publicitaire',
  'Section 10', 'RETRAIT DU CONTENU', 'Les Créateurs peuvent demander le retrait de leur contenu pour quelque raison que ce soit en écrivant à :', 'contact@worldculturemarketplace.com',
  'WCM peut également retirer un contenu si celui-ci :', 'enfreint les présentes Conditions', 'fait l’objet de plaintes culturelles ou juridiques crédibles', 'porte atteinte à la propriété intellectuelle',
  'cause un préjudice à des communautés ou à des personnes', 'est trompeur, frauduleux ou inapproprié', 'porte atteinte à la réputation ou à la mission de WCM',
  '* Le contenu retiré peut rester temporairement dans les sauvegardes du système à des fins de conformité légale et de sécurité.', 'Section 11',
  'SUSPENSION OU RÉSILIATION DU COMPTE CRÉATEUR', 'WCM peut suspendre ou résilier un compte créateur pour les motifs suivants :', 'violations répétées', 'comportement préjudiciable',
  'appropriation culturelle abusive', 'violation de droits d’auteur', 'harcèlement d’utilisateurs', 'comportement dangereux ou abusif',
  'Les Créateurs peuvent demander la suppression de leur compte à tout moment.', 'Contacter l’assistance', 'Section 12', 'AUCUNE GARANTIE DE VISIBILITÉ OU DE RÉMUNÉRATION',
  'Sauf accord écrit explicite :', 'WCM ne rémunère pas les Créateurs pour leurs soumissions', 'WCM ne garantit ni visibilité ni engagement',
  'WCM ne garantit pas la mise en avant du contenu', 'WCM ne garantit aucun résultat commercial',
  'La visibilité dépend des algorithmes de la plateforme et des décisions éditoriales.', 'Section 13', 'LIMITATION DE RESPONSABILITÉ',
  'Dans toute la mesure permise par la loi,', 'décline toute responsabilité concernant :', 'les litiges impliquant du contenu soumis par des créateurs',
  'l’utilisation ou l’usage abusif du contenu publié par des tiers', 'les désaccords ou interprétations erronées d’ordre culturel', 'les répercussions sur la réputation des Créateurs',
  'les dommages résultant de la publication ou du retrait', 'Les Créateurs publient sur WCM à leurs propres risques.', 'Section 14', 'FORCE MAJEURE',
  'ne saurait être tenue responsable d’un manquement ou d’un retard résultant d’événements échappant raisonnablement à son contrôle, notamment :',
  'Défaillances techniques', 'Interruptions du système', 'Événements extérieurs', '* Cela comprend tout événement échappant au contrôle raisonnable de la plateforme et de ses opérateurs.',
  'Section 15', 'MODIFICATIONS DU PRÉSENT ACCORD', 'WCM peut modifier périodiquement les présentes Conditions pour les créateurs afin de tenir compte de l’évolution de la plateforme ou de changements juridiques.',
  'Les modifications prennent effet dès leur publication', 'Veuillez consulter régulièrement cette page afin de prendre connaissance des éventuelles révisions.', 'DERNIÈRE MISE À JOUR :',
  'Section 16', 'COORDONNÉES', 'Pour toute question, préoccupation ou demande de retrait relative aux présentes Conditions, veuillez contacter l’équipe de',
  'WCM.', 'Adresse e-mail officielle', 'Adresse professionnelle', '50 Avenue des Champs-Élysées, 75008 Paris, France.', 'Washington, États-Unis.',
  '©', 'World Culture Marketplace. Tous droits réservés.', 'Patrimoine mondial • Découverte numérique', 'Section 17', 'DROIT APPLICABLE',
  'Les présentes Conditions sont régies et interprétées conformément au', 'droit français',
  'Tout litige relève de la compétence exclusive des', 'tribunaux de Paris, France', ', sauf disposition contraire de la loi applicable.',
  'Fin de l’Accord',
]) });
