export const PRIVACY_POLICY_PAGE_KEY = 'privacy-policy';

export const privacyPolicyContent = Object.freeze({ segments: Object.freeze([
  'Privacy', 'Policy', 'World Culture Marketplace (WCM)', 'Last updated', '25 February 2026', 'This Privacy Policy explains how',
  'World Culture Marketplace ("WCM", "we", "us", "our")', 'collects, stores, processes, and protects your personal data when you visit or use',
  'worldculturemarketplace.com', '(the "Platform").', 'We comply with:', 'The General Data Protection Regulation (GDPR)',
  'The French Data Protection Act (Loi Informatique et Libertés) if operating in France', 'Applicable global privacy laws',
  'By using the Platform, you consent to the practices described in this Privacy Policy.', 'Section 01', 'Data We Collect',
  'We collect several types of personal and non-personal data.', '1.1 — Data You Provide Directly', 'When you use WCM, you may provide:',
  'Name', 'Email address', 'Username', 'Password (securely hashed)', 'Cultural contributions and descriptions', 'Creator profile details',
  'Communications sent to WCM', 'Advertising inquiries or submissions', 'Uploaded files (images, text, media)',
  '1.2 — Data Collected Automatically', 'Through analytics tools, cookies, and log files, we collect:', 'IP address',
  'Browser type and version', 'Device type', 'Operating system', 'Pages visited', 'Time spent on each page', 'Click behavior and interactions',
  'Referring URLs', 'Approximate geolocation (non-precise)', 'This data is pseudonymized when possible.', '1.3 — Data from Third Parties',
  'We may receive additional data from:', 'Google Analytics', 'Meta (Facebook/Instagram) Pixel', 'Advertising networks',
  'Social login tools (if enabled)', 'This may include anonymized user behavior and ad performance data.', 'Section 02',
  'Why We Process Your Data (GDPR Legal Basis)', 'Under GDPR, we process your data on the following legal bases:', '2.1 — Consent',
  'Given when you:', 'accept cookies', 'subscribe to a newsletter', 'submit content', 'request communication', '2.2 — Contract Performance',
  'We process data necessary to:', 'register and manage your account', 'allow you to submit content', 'enable creators to publish profiles',
  'provide advertising services', '2.3 — Legitimate Interests', 'We process certain data to:', 'secure and maintain the Platform',
  'improve performance', 'analyze usage', 'detect fraud or abuse', 'protect cultural integrity', '2.4 — Legal Obligations',
  'We may process data for:', 'record-keeping', 'compliance with laws', 'responding to lawful requests', 'Section 03', 'How We Use Your Data',
  'Operate the Platform', 'Authenticate users', 'Publish and display cultural content', 'Provide creator tools and visibility',
  'Improve user experience', 'Protect the Platform from misuse', 'Comply with GDPR and other laws',
  'Communicate updates, alerts, or support messages', 'Analyze site traffic and trends', 'Support advertising and visibility features',
  '✓', 'We do', 'not', 'sell personal data.', 'Section 04', 'Cookies and Tracking Technologies', 'We use cookies for',
  'Essential site functionality', 'Login sessions', 'User preferences', 'Analytics and performance', 'Advertising measurement', 'You may',
  'Accept or reject non-essential cookies', 'Customize cookie preferences', 'Revoke consent at any time', 'See the', 'Cookie Policy',
  'for full details.', 'Section 05', 'How We Share Your Data', '5.1 — Service Providers',
  'Such as: hosting providers, analytics tools, advertising partners, backup systems, email service providers. All service providers operate under strict confidentiality agreements.',
  '5.2 — Legal Authorities', 'If required by court order, law enforcement, or regulatory obligations.', '5.3 — Other Users',
  'If you are a creator: your name, profile, and cultural content may be publicly visible.', '5.4 — Business Transfers',
  'If WCM undergoes a merger, data may transfer under equal protection conditions.', 'Data Security', 'SSL encryption', 'Password hashing',
  'Limited access controls', 'Firewall protection', 'Regular backups', 'No system is 100% secure, but we use industry standards.',
  'Data Retention', 'User accounts → until deleted', 'Creator content → until removal requested', 'Analytics → per Google settings',
  'International Transfers', 'Data transferred outside the EU uses SCCs and GDPR-compliant processors.', 'SECTION', 'Section 09',
  'Your Rights Under GDPR', 'Right of Access', 'Request copies of your personal data.', 'Right to Rectification', 'Correct inaccurate data.',
  'Right to Erasure', 'Request deletion ("right to be forgotten").', 'Right to Restriction', 'Limit how we process your data.',
  'Right to Object', 'Object to certain processing activities.', 'Right to Portability', 'Receive your data in a portable format.',
  'Right to Withdraw Consent', 'Revoke consent at any time.', 'Right to Complain', 'Lodge a complaint with a supervisory authority.',
  "Children's Privacy", 'Not intended for children under 16.', 'Third-Party Links', 'WCM is not responsible for external site policies.',
  'Changes to This Policy', 'We may update this Policy periodically. Continued use of the Platform after changes constitutes acceptance.',
  'Section 16', 'Contact Information', 'contact@worldculturemarketplace.com', '50 Avenue des Champs-Élysées, 75008 Paris, France.',
  '🇺🇸 Washington, USA.', '06', '07', '08', '9.1', '9.2', '9.3', '9.4', '9.5', '9.6', '9.7', '9.8', '10', '11', '12', '.', ':',
]) });

export const privacyPolicyFrenchContent = Object.freeze({ segments: Object.freeze([
  'Confidentialité', 'Politique', 'World Culture Marketplace (WCM)', 'Dernière mise à jour', '25 février 2026', 'La présente Politique de confidentialité explique comment',
  'World Culture Marketplace (« WCM », « nous », « notre », « nos »)', 'collecte, conserve, traite et protège vos données personnelles lorsque vous consultez ou utilisez',
  'worldculturemarketplace.com', '(la « Plateforme »).', 'Nous respectons :', 'le Règlement général sur la protection des données (RGPD)',
  'la loi française Informatique et Libertés lorsque nos activités sont exercées en France', 'les lois applicables en matière de protection de la vie privée dans le monde',
  'En utilisant la Plateforme, vous consentez aux pratiques décrites dans la présente Politique de confidentialité.', 'Section 01', 'Données que nous collectons',
  'Nous collectons plusieurs types de données personnelles et non personnelles.', '1.1 — Données que vous fournissez directement', 'Lorsque vous utilisez WCM, vous pouvez fournir :',
  'Nom', 'Adresse e-mail', 'Nom d’utilisateur', 'Mot de passe (haché de manière sécurisée)', 'Contributions et descriptions culturelles', 'Informations du profil créateur',
  'Communications adressées à WCM', 'Demandes ou soumissions publicitaires', 'Fichiers téléversés (images, textes, médias)',
  '1.2 — Données collectées automatiquement', 'Nous collectons, au moyen d’outils d’analyse, de cookies et de fichiers journaux :', 'Adresse IP',
  'Type et version du navigateur', 'Type d’appareil', 'Système d’exploitation', 'Pages consultées', 'Temps passé sur chaque page', 'Clics et interactions',
  'URL de provenance', 'Géolocalisation approximative (non précise)', 'Ces données sont pseudonymisées lorsque cela est possible.', '1.3 — Données provenant de tiers',
  'Nous pouvons recevoir des données supplémentaires de la part de :', 'Google Analytics', 'Pixel Meta (Facebook/Instagram)', 'Régies publicitaires',
  'Outils de connexion sociale (si activés)', 'Ces données peuvent inclure des informations anonymisées sur le comportement des utilisateurs et les performances publicitaires.', 'Section 02',
  'Pourquoi nous traitons vos données (base juridique du RGPD)', 'En vertu du RGPD, nous traitons vos données sur les bases juridiques suivantes :', '2.1 — Consentement',
  'Donné lorsque vous :', 'acceptez les cookies', 'vous abonnez à une newsletter', 'soumettez du contenu', 'demandez à être contacté', '2.2 — Exécution du contrat',
  'Nous traitons les données nécessaires pour :', 'enregistrer et gérer votre compte', 'vous permettre de soumettre du contenu', 'permettre aux créateurs de publier leur profil',
  'fournir des services publicitaires', '2.3 — Intérêts légitimes', 'Nous traitons certaines données pour :', 'sécuriser et maintenir la Plateforme',
  'améliorer les performances', 'analyser l’utilisation', 'détecter la fraude ou les abus', 'protéger l’intégrité culturelle', '2.4 — Obligations légales',
  'Nous pouvons traiter des données pour :', 'tenir des registres', 'respecter les lois', 'répondre aux demandes légales', 'Section 03', 'Utilisation de vos données',
  'Exploiter la Plateforme', 'Authentifier les utilisateurs', 'Publier et afficher du contenu culturel', 'Fournir aux créateurs des outils et de la visibilité',
  'Améliorer l’expérience utilisateur', 'Protéger la Plateforme contre les abus', 'Respecter le RGPD et les autres lois',
  'Communiquer des mises à jour, alertes ou messages d’assistance', 'Analyser le trafic et les tendances du site', 'Prendre en charge les fonctionnalités publicitaires et de visibilité',
  '✓', 'Nous ne', 'vendons', 'aucune donnée personnelle.', 'Section 04', 'Cookies et technologies de suivi', 'Nous utilisons des cookies pour',
  'Les fonctionnalités essentielles du site', 'Les sessions de connexion', 'Les préférences utilisateur', 'L’analyse et les performances', 'La mesure publicitaire', 'Vous pouvez',
  'Accepter ou refuser les cookies non essentiels', 'Personnaliser vos préférences de cookies', 'Retirer votre consentement à tout moment', 'Consultez la', 'Politique relative aux cookies',
  'pour obtenir tous les détails.', 'Section 05', 'Partage de vos données', '5.1 — Prestataires de services',
  'Par exemple : hébergeurs, outils d’analyse, partenaires publicitaires, systèmes de sauvegarde et prestataires de messagerie. Tous les prestataires sont soumis à des accords de confidentialité stricts.',
  '5.2 — Autorités légales', 'Lorsque cela est requis par une décision de justice, les forces de l’ordre ou des obligations réglementaires.', '5.3 — Autres utilisateurs',
  'Si vous êtes créateur, votre nom, votre profil et votre contenu culturel peuvent être visibles publiquement.', '5.4 — Transferts d’entreprise',
  'En cas de fusion impliquant WCM, les données peuvent être transférées sous réserve de conditions de protection équivalentes.', 'Sécurité des données', 'Chiffrement SSL', 'Hachage des mots de passe',
  'Contrôles d’accès limités', 'Protection par pare-feu', 'Sauvegardes régulières', 'Aucun système n’est sécurisé à 100 %, mais nous appliquons les normes du secteur.',
  'Conservation des données', 'Comptes utilisateur → jusqu’à leur suppression', 'Contenu des créateurs → jusqu’à la demande de retrait', 'Données analytiques → selon les paramètres de Google',
  'Transferts internationaux', 'Les données transférées hors de l’UE utilisent les clauses contractuelles types et des sous-traitants conformes au RGPD.', 'SECTION', 'Section 09',
  'Vos droits en vertu du RGPD', 'Droit d’accès', 'Demander une copie de vos données personnelles.', 'Droit de rectification', 'Corriger des données inexactes.',
  'Droit à l’effacement', 'Demander la suppression (« droit à l’oubli »).', 'Droit à la limitation', 'Limiter la manière dont nous traitons vos données.',
  'Droit d’opposition', 'Vous opposer à certaines activités de traitement.', 'Droit à la portabilité', 'Recevoir vos données dans un format portable.',
  'Droit de retirer son consentement', 'Retirer votre consentement à tout moment.', 'Droit d’introduire une réclamation', 'Déposer une réclamation auprès d’une autorité de contrôle.',
  'Protection de la vie privée des enfants', 'La Plateforme n’est pas destinée aux enfants de moins de 16 ans.', 'Liens vers des sites tiers', 'WCM n’est pas responsable des politiques des sites externes.',
  'Modifications de la présente Politique', 'Nous pouvons mettre à jour périodiquement la présente Politique. La poursuite de l’utilisation de la Plateforme après les modifications vaut acceptation.',
  'Section 16', 'Coordonnées', 'contact@worldculturemarketplace.com', '50 Avenue des Champs-Élysées, 75008 Paris, France.',
  '🇺🇸 Washington, États-Unis.', '06', '07', '08', '9.1', '9.2', '9.3', '9.4', '9.5', '9.6', '9.7', '9.8', '10', '11', '12', '.', ':',
]) });
