export const termsAndConditionsContent = Object.freeze({ segments: Object.freeze([
  'Introduction', 'Definitions', 'About WCM', 'Eligibility', 'Account Registration', 'Acceptable Use Policy', 'Platform Content',
  'Intellectual Property Rights', 'Third-Party Links', 'Advertising Services', 'Disclaimers', 'Limitation of Liability',
  'Privacy & GDPR', 'Termination', 'Governing Law', 'Contact Information', 'Terms &', 'Conditions',
  'World Culture Marketplace (WCM)', 'Last updated', '25 February 2026', 'Table of Contents', 'Section 01',
  'Welcome to World Culture Marketplace ("WCM", "we", "us", "our"). These Terms & Conditions ("Terms") govern your access to and use of the website',
  'worldculturemarketplace.com', '(the "Platform").',
  'By accessing or using the Platform, you agree to be bound by these Terms. If you do not agree, please do not use the Platform.',
  'WCM is a cultural discovery and visibility platform intended to share, celebrate, and promote global cultural knowledge, creators, and traditions.',
  'Section 02', 'For clarity in this document:', '"Platform"', 'The WCM website and all related digital services.', '"User"',
  'Any person accessing or using the Platform.', '"Creator"', 'Users who submit cultural content, profiles, or media.', '"Content"',
  'Text, images, audio, video, descriptions, links, and any materials uploaded or displayed on the Platform.', '"Advertiser"',
  'Any user or organization purchasing promotional or visibility services.', '"Services"',
  'All features provided by WCM, including browsing, cultural content, creator profiles, advertising tools, and platform functionality.',
  'Section 03', 'WCM is a platform designed to:', 'Promote cultural diversity and visibility.',
  'Share educational, historical, and artistic content.', 'Support creators, storytellers, and cultural advocates.',
  'Enable promotional and advertising opportunities.',
  'WCM does not currently provide e-commerce transaction services. The Platform focuses on cultural content, visibility, and external redirection to third-party websites. E-commerce features may be introduced in future versions.',
  'WCM does not verify the academic or historical accuracy of every cultural contribution and is not responsible for interpretative differences.',
  'Section 04', 'You may use the Platform only if:', 'You are at least 16 years old, or the minimum required age in your jurisdiction.',
  'You have the legal capacity to accept these Terms.', 'You use the Platform in compliance with all applicable laws.',
  'If creating a creator profile, you represent that all submitted information is accurate and lawful.', 'Section 05',
  'Users may create an account to access certain features. You agree to:', 'Provide accurate and truthful information.',
  'Keep login credentials confidential.', 'Notify WCM immediately of unauthorized access.', 'Not share or sell your account.',
  'WCM may suspend or terminate accounts that violate these Terms.', 'Section 06', 'Users agree', 'NOT', 'to:',
  'Use the Platform for illegal, harmful, fraudulent, or abusive purposes.', 'Upload malware, harmful scripts, or malicious files.',
  'Harvest or collect personal data from other users.', 'Attempt to hack, disrupt, or reverse-engineer the Platform.',
  'Upload culturally offensive or disrespectful content.', 'Impersonate any person, culture, community, or organization.',
  'Scrape or copy Platform content for resale or reproduction.', 'Violations may result in permanent account termination.', 'Section 07',
  '7.1 — WCM Content',
  'All content created by WCM — including articles, categories, stories, images, branding, and platform architecture — is protected by intellectual property laws.',
  'You may', 'copy, reproduce, redistribute, modify, or publish WCM content without written approval.', '7.2 — User-Generated Content',
  'Creators retain ownership of their submitted content.', 'By submitting content, you grant WCM a',
  'non-exclusive, worldwide, royalty-free, transferable license',
  "to publish, display, host, distribute, adapt, and promote your content as part of the Platform's operations.",
  'You own the rights to your content.', 'Your content does not infringe third-party rights.',
  'Your content is culturally respectful and accurate to the best of your knowledge.', '✓',
  'WCM may remove content that violates guidelines or legal requirements.', 'Section 08',
  'All trademarks, logos, branding, design elements, and platform architecture are the exclusive property of WCM.', 'Users may not:',
  'Use WCM trademarks without permission.', 'Reproduce WCM brand elements.', 'Claim ownership of WCM intellectual property.',
  'Creators retain ownership of their content subject to the license granted in Section 7.', 'Section 09', 'WCM may include links to',
  'External websites', 'Creator social media', 'Business sites', 'Educational resources', 'WCM is not responsible for',
  'Third-party privacy practices', 'Content accuracy', 'Transactions performed outside WCM', 'Harm arising from external websites',
  'Users navigate external links at their own risk.', 'Section 10', 'WCM may offer:', 'Banner ads', 'Sponsored cultural content',
  'Boosted visibility', 'PPC-based advertising', 'All advertising activities are governed by the', 'Advertising Terms',
  ', which form part of this legal suite.', 'Section 11', 'WCM provides the Platform', '"as is"', 'without guarantees of:',
  'Uninterrupted operation', 'Accuracy of cultural information', 'Error-free performance', 'Continuous availability',
  'Completeness of user-submitted content', 'Academic certification',
  '"WCM does not provide academic or anthropological certification of cultural content."', 'Section 12',
  'To the maximum extent permitted by law, WCM is', 'not liable', 'for:', 'Loss of data', 'Loss of revenue',
  'Indirect or consequential damages', 'Cultural interpretation disputes', 'Reliance on user-generated content',
  'Unauthorized access to user accounts', 'Your use of the Platform is at your own risk.', 'Section 13',
  'Your data is governed by the', 'WCM Privacy Policy', ', which is incorporated into these Terms.', 'This includes information on:',
  'Data collection', 'Cookies', 'GDPR rights', 'Data retention', 'Security measures', 'Section 14',
  'WCM may suspend or terminate accounts for:', 'Violating these Terms', 'Harmful or abusive behavior', 'Cultural misrepresentation',
  'Copyright infringement', 'Security risks', 'Users may request account deletion at any time.', 'Section 15',
  'These Terms are governed by the laws of the jurisdiction in which WCM operates. Any disputes shall be resolved in the competent courts of that jurisdiction.',
  'Section 16', 'contact@worldculturemarketplace.com', '50 Avenue des Champs-Élysées, 75008 Paris, France', 'Washington, USA',
]) });

export const termsAndConditionsFrenchContent = Object.freeze({ segments: Object.freeze([
  'Introduction', 'Définitions', 'À propos de WCM', 'Éligibilité', 'Création d’un compte', 'Politique d’utilisation acceptable', 'Contenu de la Plateforme',
  'Droits de propriété intellectuelle', 'Liens vers des sites tiers', 'Services publicitaires', 'Exclusions de garantie', 'Limitation de responsabilité',
  'Confidentialité et RGPD', 'Résiliation', 'Droit applicable', 'Coordonnées', 'Conditions', 'générales',
  'World Culture Marketplace (WCM)', 'Dernière mise à jour', '25 février 2026', 'Table des matières', 'Section 01',
  'Bienvenue sur World Culture Marketplace (« WCM », « nous », « notre », « nos »). Les présentes Conditions générales (« Conditions ») régissent votre accès au site web et son utilisation',
  'worldculturemarketplace.com', '(la « Plateforme »).',
  'En accédant à la Plateforme ou en l’utilisant, vous acceptez d’être lié par les présentes Conditions. Si vous ne les acceptez pas, veuillez ne pas utiliser la Plateforme.',
  'WCM est une plateforme de découverte et de visibilité culturelles destinée à partager, célébrer et promouvoir les savoirs, créateurs et traditions du monde entier.',
  'Section 02', 'Aux fins du présent document :', '« Plateforme »', 'Le site web WCM et tous les services numériques associés.', '« Utilisateur »',
  'Toute personne qui accède à la Plateforme ou l’utilise.', '« Créateur »', 'Les Utilisateurs qui soumettent du contenu culturel, des profils ou des médias.', '« Contenu »',
  'Les textes, images, contenus audio, vidéos, descriptions, liens et tout élément téléversé ou affiché sur la Plateforme.', '« Annonceur »',
  'Tout utilisateur ou toute organisation qui achète des services promotionnels ou de visibilité.', '« Services »',
  'Toutes les fonctionnalités fournies par WCM, notamment la navigation, le contenu culturel, les profils de créateurs, les outils publicitaires et les fonctionnalités de la Plateforme.',
  'Section 03', 'WCM est une plateforme conçue pour :', 'Promouvoir la diversité et la visibilité culturelles.',
  'Partager des contenus éducatifs, historiques et artistiques.', 'Soutenir les créateurs, conteurs et défenseurs des cultures.',
  'Offrir des possibilités de promotion et de publicité.',
  'WCM ne fournit actuellement aucun service de transaction de commerce électronique. La Plateforme est consacrée au contenu culturel, à la visibilité et à la redirection externe vers des sites tiers. Des fonctionnalités de commerce électronique pourront être ajoutées dans de futures versions.',
  'WCM ne vérifie pas l’exactitude académique ou historique de chaque contribution culturelle et décline toute responsabilité concernant les différences d’interprétation.',
  'Section 04', 'Vous pouvez utiliser la Plateforme uniquement si :', 'Vous avez au moins 16 ans, ou l’âge minimum requis dans votre juridiction.',
  'Vous avez la capacité juridique d’accepter les présentes Conditions.', 'Vous utilisez la Plateforme conformément à toutes les lois applicables.',
  'Si vous créez un profil de créateur, vous déclarez que toutes les informations soumises sont exactes et licites.', 'Section 05',
  'Les Utilisateurs peuvent créer un compte pour accéder à certaines fonctionnalités. Vous acceptez de :', 'Fournir des informations exactes et sincères.',
  'Garder vos identifiants de connexion confidentiels.', 'Informer immédiatement WCM de tout accès non autorisé.', 'Ne pas partager ni vendre votre compte.',
  'WCM peut suspendre ou résilier les comptes qui enfreignent les présentes Conditions.', 'Section 06', 'Les Utilisateurs acceptent de', 'NE PAS', ':',
  'Utiliser la Plateforme à des fins illégales, préjudiciables, frauduleuses ou abusives.', 'Téléverser des logiciels malveillants, scripts nuisibles ou fichiers malveillants.',
  'Extraire ou collecter les données personnelles d’autres utilisateurs.', 'Tenter de pirater, perturber ou désosser la Plateforme.',
  'Téléverser du contenu offensant ou irrespectueux sur le plan culturel.', 'Usurper l’identité d’une personne, d’une culture, d’une communauté ou d’une organisation.',
  'Extraire ou copier le contenu de la Plateforme à des fins de revente ou de reproduction.', 'Toute violation peut entraîner la résiliation définitive du compte.', 'Section 07',
  '7.1 — Contenu WCM',
  'Tout contenu créé par WCM — notamment les articles, catégories, récits, images, éléments de marque et architecture de la Plateforme — est protégé par les lois relatives à la propriété intellectuelle.',
  'Vous ne pouvez', 'copier, reproduire, redistribuer, modifier ou publier le contenu WCM sans autorisation écrite.', '7.2 — Contenu généré par les utilisateurs',
  'Les Créateurs restent propriétaires du contenu qu’ils soumettent.', 'En soumettant du contenu, vous accordez à WCM une',
  'licence non exclusive, mondiale, gratuite et transférable',
  'permettant de publier, afficher, héberger, distribuer, adapter et promouvoir votre contenu dans le cadre des activités de la Plateforme.',
  'Vous détenez les droits sur votre contenu.', 'Votre contenu ne porte pas atteinte aux droits de tiers.',
  'Votre contenu respecte les cultures et est exact au meilleur de votre connaissance.', '✓',
  'WCM peut retirer tout contenu qui enfreint les règles ou les exigences légales.', 'Section 08',
  'Toutes les marques, tous les logos, éléments de marque, éléments graphiques et l’architecture de la Plateforme sont la propriété exclusive de WCM.', 'Les Utilisateurs ne peuvent pas :',
  'Utiliser les marques de WCM sans autorisation.', 'Reproduire les éléments de marque de WCM.', 'Revendiquer la propriété intellectuelle de WCM.',
  'Les Créateurs restent propriétaires de leur contenu sous réserve de la licence accordée à la Section 7.', 'Section 09', 'WCM peut inclure des liens vers',
  'Des sites web externes', 'Les réseaux sociaux des Créateurs', 'Des sites professionnels', 'Des ressources éducatives', 'WCM décline toute responsabilité concernant',
  'Les pratiques de confidentialité des tiers', 'L’exactitude du contenu', 'Les transactions effectuées en dehors de WCM', 'Les préjudices résultant de sites web externes',
  'Les Utilisateurs consultent les liens externes à leurs propres risques.', 'Section 10', 'WCM peut proposer :', 'Des bannières publicitaires', 'Du contenu culturel sponsorisé',
  'Une visibilité boostée', 'De la publicité basée sur le PPC', 'Toutes les activités publicitaires sont régies par les', 'Conditions publicitaires',
  ', qui font partie du présent ensemble juridique.', 'Section 11', 'WCM fournit la Plateforme', '« en l’état »', 'sans garantie concernant :',
  'Un fonctionnement ininterrompu', 'L’exactitude des informations culturelles', 'Un fonctionnement sans erreur', 'Une disponibilité continue',
  'L’exhaustivité du contenu soumis par les utilisateurs', 'Une certification académique',
  '« WCM ne fournit aucune certification académique ou anthropologique du contenu culturel. »', 'Section 12',
  'Dans toute la mesure permise par la loi, WCM', 'décline toute responsabilité', 'concernant :', 'La perte de données', 'La perte de revenus',
  'Les dommages indirects ou consécutifs', 'Les litiges liés à l’interprétation culturelle', 'La confiance accordée au contenu généré par les utilisateurs',
  'L’accès non autorisé aux comptes utilisateur', 'Vous utilisez la Plateforme à vos propres risques.', 'Section 13',
  'Vos données sont régies par la', 'Politique de confidentialité de WCM', ', qui est intégrée aux présentes Conditions.', 'Elle contient notamment des informations sur :',
  'La collecte des données', 'Les cookies', 'Les droits conférés par le RGPD', 'La conservation des données', 'Les mesures de sécurité', 'Section 14',
  'WCM peut suspendre ou résilier un compte pour les motifs suivants :', 'Violation des présentes Conditions', 'Comportement préjudiciable ou abusif', 'Présentation culturelle inexacte',
  'Violation de droits d’auteur', 'Risques de sécurité', 'Les Utilisateurs peuvent demander la suppression de leur compte à tout moment.', 'Section 15',
  'Les présentes Conditions sont régies par les lois de la juridiction dans laquelle WCM exerce ses activités. Tout litige sera tranché par les tribunaux compétents de cette juridiction.',
  'Section 16', 'contact@worldculturemarketplace.com', '50 Avenue des Champs-Élysées, 75008 Paris, France', 'Washington, États-Unis',
]) });

export const cookiePolicyContent = Object.freeze({ segments: Object.freeze([
  'What Are Cookies?', 'Types of Cookies We Use', 'How We Obtain Consent', 'Third-Party Cookies', 'How to Manage or Disable Cookies',
  'Data Stored by Cookies', 'Changes to This Cookie Policy', 'Contact Information', 'Cookie', 'Policy', 'World Culture Marketplace (WCM)',
  'Last updated', '15 March 2025', 'This Cookie Policy explains how World Culture Marketplace ("WCM", "we", "our") uses cookies and similar tracking technologies on',
  'worldculturemarketplace.com', '.', 'By using the Platform, you agree to the storage and use of cookies as described in this Policy.',
  'Table of Contents', 'Section 01', 'Cookies are small text files stored on your device when visiting a website. They allow WCM to:',
  'Remember your preferences', 'Improve performance', 'Measure traffic', 'Display content correctly', 'Support advertising features',
  'Cookie Types by Lifespan', 'Session Cookies', 'Deleted upon closing your browser', 'Persistent Cookies',
  'Remain on your device for a set period', 'First-Party Cookies', 'Placed directly by WCM', 'Placed by analytics or advertising partners',
  'Section 02', 'WCM uses four main categories of cookies.', '2.1 — Essential Cookies (Strictly Necessary)', 'Enabling basic site functionality',
  'Secure login and session management', 'Load balancing', 'Preventing fraud or abuse', '2.2 — Performance & Analytics Cookies',
  'Page popularity and navigation patterns', 'Session duration and device types', 'Traffic sources', '2.3 — Preference & Functionality Cookies',
  'Preferred language and region', 'Display choices', 'Saved settings', '2.4 — Advertising & Marketing Cookies', 'Track ad performance',
  'Support boosted listings', 'Measure clicks and impressions', 'Personalize visibility', 'Enable retargeting',
  'You may disable Advertising & Marketing Cookies through our cookie banner or browser settings.', 'Section 03',
  'WCM complies with GDPR cookie consent requirements. Upon your first visit, the Platform displays a', 'Cookie Consent Banner', ', allowing you to:',
  '✓', 'Accept all cookies', '✕', 'Reject non-essential cookies', '⚙', 'Customize cookie categories',
  'Your preferences are stored and may be changed at any time.', 'Section 04',
  'Some cookies come from third parties integrated into the Platform, including:', 'Analytics providers', 'Embedded video platforms',
  'Social media widgets', 'Advertising networks', 'WCM does not control or govern third-party cookie behavior.',
  "These providers may use cookies independently. Users should review each provider's privacy policy for more details.", 'Section 05',
  'You can control cookies in three ways:', '5.1 — Website Cookie Settings',
  'Use the cookie banner or settings panel to enable, disable, or customize non-essential cookies.', '5.2 — Browser Settings',
  'Most browsers allow you to:', 'Block all cookies', 'Block third-party cookies', 'Delete cookies', 'Clear browsing data',
  'Instructions vary across Chrome, Safari, Firefox, Edge, and mobile browsers.', '5.3 — Opt-Out Tools',
  'For analytics and advertising, you may use:', 'Google Analytics Opt-Out Browser Add-On', 'Meta Ads Preference Center',
  'Advertising industry opt-out pages', 'Some features may become unavailable if you disable all cookies.', 'Section 06',
  'Cookies may store', 'Session identifiers', 'Device type', 'Browser type', 'IP address (anonymized when possible)', 'Navigation history',
  'Ad interaction data', 'Cookies do NOT store', 'Passwords', 'Payment information', 'Sensitive personal data', 'Section 07',
  'WCM may update this Policy without prior notice. Updates will be reflected with a new "Last updated" date at the top of this page.',
  'We encourage you to review this Policy periodically to stay informed about how we use cookies.', 'Section 08',
  'contact@worldculturemarketplace.com', '50 Avenue des Champs-Élysées, 75008 Paris, France', 'Washington, USA',
]) });

export const cookiePolicyFrenchContent = Object.freeze({ segments: Object.freeze([
  'Que sont les cookies ?', 'Types de cookies que nous utilisons', 'Comment nous recueillons votre consentement', 'Cookies tiers', 'Comment gérer ou désactiver les cookies',
  'Données stockées par les cookies', 'Modifications de la présente Politique relative aux cookies', 'Coordonnées', 'Cookies', 'Politique', 'World Culture Marketplace (WCM)',
  'Dernière mise à jour', '15 mars 2025', 'La présente Politique explique comment World Culture Marketplace (« WCM », « nous », « notre ») utilise des cookies et des technologies de suivi similaires sur',
  'worldculturemarketplace.com', '.', 'En utilisant la Plateforme, vous acceptez le stockage et l’utilisation de cookies tels que décrits dans la présente Politique.',
  'Table des matières', 'Section 01', 'Les cookies sont de petits fichiers texte stockés sur votre appareil lorsque vous consultez un site web. Ils permettent à WCM de :',
  'Mémoriser vos préférences', 'Améliorer les performances', 'Mesurer le trafic', 'Afficher correctement le contenu', 'Prendre en charge les fonctionnalités publicitaires',
  'Types de cookies selon leur durée de vie', 'Cookies de session', 'Supprimés à la fermeture de votre navigateur', 'Cookies persistants',
  'Restent sur votre appareil pendant une période déterminée', 'Cookies internes', 'Déposés directement par WCM', 'Déposés par des partenaires d’analyse ou de publicité',
  'Section 02', 'WCM utilise quatre grandes catégories de cookies.', '2.1 — Cookies essentiels (strictement nécessaires)', 'Activer les fonctionnalités de base du site',
  'Sécuriser la connexion et gérer les sessions', 'Répartir la charge', 'Prévenir la fraude ou les abus', '2.2 — Cookies de performance et d’analyse',
  'Popularité des pages et habitudes de navigation', 'Durée des sessions et types d’appareils', 'Sources de trafic', '2.3 — Cookies de préférence et de fonctionnalité',
  'Langue et région préférées', 'Choix d’affichage', 'Paramètres enregistrés', '2.4 — Cookies publicitaires et marketing', 'Suivre les performances publicitaires',
  'Prendre en charge les annonces boostées', 'Mesurer les clics et les impressions', 'Personnaliser la visibilité', 'Activer le reciblage',
  'Vous pouvez désactiver les cookies publicitaires et marketing depuis notre bandeau de cookies ou les paramètres de votre navigateur.', 'Section 03',
  'WCM respecte les exigences du RGPD relatives au consentement aux cookies. Lors de votre première visite, la Plateforme affiche un', 'Bandeau de consentement aux cookies', ', qui vous permet de :',
  '✓', 'Accepter tous les cookies', '✕', 'Refuser les cookies non essentiels', '⚙', 'Personnaliser les catégories de cookies',
  'Vos préférences sont enregistrées et peuvent être modifiées à tout moment.', 'Section 04',
  'Certains cookies proviennent de tiers intégrés à la Plateforme, notamment :', 'Des fournisseurs de services d’analyse', 'Des plateformes de vidéos intégrées',
  'Des widgets de réseaux sociaux', 'Des régies publicitaires', 'WCM ne contrôle ni ne régit le comportement des cookies tiers.',
  'Ces fournisseurs peuvent utiliser des cookies de manière indépendante. Les Utilisateurs doivent consulter la politique de confidentialité de chaque fournisseur pour plus de détails.', 'Section 05',
  'Vous pouvez contrôler les cookies de trois manières :', '5.1 — Paramètres des cookies du site web',
  'Utilisez le bandeau de cookies ou le panneau de paramètres pour activer, désactiver ou personnaliser les cookies non essentiels.', '5.2 — Paramètres du navigateur',
  'La plupart des navigateurs vous permettent de :', 'Bloquer tous les cookies', 'Bloquer les cookies tiers', 'Supprimer les cookies', 'Effacer les données de navigation',
  'Les instructions varient selon Chrome, Safari, Firefox, Edge et les navigateurs mobiles.', '5.3 — Outils de désactivation',
  'Pour l’analyse et la publicité, vous pouvez utiliser :', 'Module complémentaire de navigateur pour la désactivation de Google Analytics', 'Centre de préférences publicitaires Meta',
  'Pages de désactivation du secteur publicitaire', 'Certaines fonctionnalités peuvent devenir indisponibles si vous désactivez tous les cookies.', 'Section 06',
  'Les cookies peuvent stocker', 'Identifiants de session', 'Type d’appareil', 'Type de navigateur', 'Adresse IP (anonymisée lorsque cela est possible)', 'Historique de navigation',
  'Données d’interaction publicitaire', 'Les cookies ne stockent PAS', 'Mots de passe', 'Informations de paiement', 'Données personnelles sensibles', 'Section 07',
  'WCM peut modifier la présente Politique sans préavis. Toute mise à jour sera signalée par une nouvelle date de « Dernière mise à jour » en haut de cette page.',
  'Nous vous encourageons à consulter régulièrement la présente Politique afin de rester informé de notre utilisation des cookies.', 'Section 08',
  'contact@worldculturemarketplace.com', '50 Avenue des Champs-Élysées, 75008 Paris, France', 'Washington, États-Unis',
]) });
